version: '3.8'

volumes:
  postgres_volume:

services:
  pg:
    container_name: postgres
    image: postgres:14-alpine3.17
    environment:
      - "POSTGRES_DB=${DB_NAME}"
      - "POSTGRES_USER=${DB_USER}"
      - "POSTGRES_PASSWORD=${DB_PASSWORD}"
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7

  nginx:
    image: nginx:1.25
    ports:
      - "9000:80"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
    depends_on:
      - pg
      - redis
